### PR TITLE
Fix rounding by passing cmp result

### LINKED ISSUE #7: `5.59` with `HalfDown` rounding should round to 6, not 5
If I have `5.59`, and rounding `HalfDown`, the rounding should go to 6, not to 5.

### PR DESCRIPTION
**Pull request by karelbilek**
This is technically an API breaking change (if someone implemented their own rounding function), but since not many people use that, I don't think it warrants a major version.

Fixes #7

### CODE REVIEW

**Comment by karel-3d** [comment]
there is something called "double rounding" which is not doable by this either

that is, we want to round 4.49 to 5, because we do 4.49->4.5->5

But I don't think it's that common, so let's keep it like this

**Comment by karel-3d** [comment]
it would be maybe modelable by this, if instead of `.Cmp(r)` we pass the difference, and you could call the rounding algorithm recursively

should I do that, or does this suffice?

**Comment by wadey** [comment]
Thanks for the PR, reviewing this now.

**Review by wadey — APPROVED** [review]
Wow, this was an embarrassing bug! Thank you for digging in and finding a good fix for it.

**Comment by karelbilek** [comment]
thx for merging :D seems this library is not very widely used, but it's actually pretty good for what I need to do

**Pull request merged**
